### ISSUE TITLE
osu namespace could not be found

### ISSUE THREAD

**Issue by MelonIs45** [GokuWeedLord/osu-meme#1]
I've have noticed that in the `Interprocess.cs` file there are 3 references to the `osu` namespace which is nowhere to be seen in the project, I'm just wondering how you got it to work while you were developing it? Thanks

**Comment by NotAdam** [comment]
they're in (or were) in the game exe itself, you need to reference it for the project to build

I've attached the old exe which had the interprocess functionality in osu.Helpers.InterProcessOsu in the event it's since been removed

[osu!.zip](https://github.com/NotAdam/osu-ipc/files/5819962/osu.zip)

**Comment by MelonIs45** [comment]
Thank you very much, that fixed the errors :)
